// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBS2Y1U61kAaRGlb-mjZsk7xA5RQ7xc5DY',
    appId: '1:544209786849:web:325ebd22c54ded227664a0',
    messagingSenderId: '544209786849',
    projectId: 'news-app-74a4b',
    authDomain: 'news-app-74a4b.firebaseapp.com',
    storageBucket: 'news-app-74a4b.firebasestorage.app',
    measurementId: 'G-QWWBB3F97M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCbCSP09O6XrrAMRBvX1HHckna2T03zwc',
    appId: '1:544209786849:android:46dd714b019ac3de7664a0',
    messagingSenderId: '544209786849',
    projectId: 'news-app-74a4b',
    storageBucket: 'news-app-74a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBX6uBb7bwqMozyLD-cBSKGouX0gaCFm9E',
    appId: '1:544209786849:ios:812889482d75d49e7664a0',
    messagingSenderId: '544209786849',
    projectId: 'news-app-74a4b',
    storageBucket: 'news-app-74a4b.firebasestorage.app',
    iosBundleId: 'com.example.myapplicationadvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBX6uBb7bwqMozyLD-cBSKGouX0gaCFm9E',
    appId: '1:544209786849:ios:812889482d75d49e7664a0',
    messagingSenderId: '544209786849',
    projectId: 'news-app-74a4b',
    storageBucket: 'news-app-74a4b.firebasestorage.app',
    iosBundleId: 'com.example.myapplicationadvanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBS2Y1U61kAaRGlb-mjZsk7xA5RQ7xc5DY',
    appId: '1:544209786849:web:75c133c6c37f9cb97664a0',
    messagingSenderId: '544209786849',
    projectId: 'news-app-74a4b',
    authDomain: 'news-app-74a4b.firebaseapp.com',
    storageBucket: 'news-app-74a4b.firebasestorage.app',
    measurementId: 'G-1DG5Y26JRR',
  );
}
